// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBkSRAAmtOJxMEdY8Cum3xHXHiPu06Z48',
    appId: '1:368408658781:web:bf893f5be33d8cc62b5eb4',
    messagingSenderId: '368408658781',
    projectId: 'koyndex-64328',
    authDomain: 'koyndex-64328.firebaseapp.com',
    storageBucket: 'koyndex-64328.firebasestorage.app',
    measurementId: 'G-ZV8DBMDF64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZAuVWTkk2UP0ZbGG49lWB3lU6cyejZs',
    appId: '1:368408658781:android:1a1b89ac3508425b2b5eb4',
    messagingSenderId: '368408658781',
    projectId: 'koyndex-64328',
    storageBucket: 'koyndex-64328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_El6jvJn5rvFhJPJ8cfZ1zbyZPxmukMs',
    appId: '1:368408658781:ios:7c9eceec9f3a3e752b5eb4',
    messagingSenderId: '368408658781',
    projectId: 'koyndex-64328',
    storageBucket: 'koyndex-64328.firebasestorage.app',
    iosBundleId: 'com.example.moneyyouApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_El6jvJn5rvFhJPJ8cfZ1zbyZPxmukMs',
    appId: '1:368408658781:ios:7c9eceec9f3a3e752b5eb4',
    messagingSenderId: '368408658781',
    projectId: 'koyndex-64328',
    storageBucket: 'koyndex-64328.firebasestorage.app',
    iosBundleId: 'com.example.moneyyouApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBkSRAAmtOJxMEdY8Cum3xHXHiPu06Z48',
    appId: '1:368408658781:web:676648e3ad296c712b5eb4',
    messagingSenderId: '368408658781',
    projectId: 'koyndex-64328',
    authDomain: 'koyndex-64328.firebaseapp.com',
    storageBucket: 'koyndex-64328.firebasestorage.app',
    measurementId: 'G-EWWD45QN83',
  );
}
